version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
